### ISSUE TITLE
MysqlConnector 1.0

### ISSUE THREAD

**Issue by adamhathcock** [MiloszKrajewski/Hangfire.Storage.MySql#1]
Now that dotnet 5 is out and Pomelo is upgrading its MysqlConnector, I need my Hangfire MySQL implementation to use it.

I'm happy to submit a PR here and help out with issues but I don't know if you're still maintaining this at all?

Any plans for this project?

Thanks!

**Comment by MiloszKrajewski** [comment]
Miss-click ;-)
Just trying to understand: if you upgrade MySqlConnector in your project to 1.0 does this driver stop working?

**Comment by adamhathcock** [comment]
1.0 changed namespaces so a lot of users of MysqlConnector need to recompile at the very least.  I don't think much else did.

**Comment by adamhathcock** [comment]
I've looked at updating this but I can't figure out Paket enough to restore and therefore build anything.

**Comment by MiloszKrajewski** [comment]
I released new version based on MySqlConnector 1.0+ and Dapper 2.0+ (I used versions with highest number of downloads from nuget).
https://www.nuget.org/packages/Hangfire.Storage.MySql/2.1.0-beta

**Comment by adamhathcock** [comment]
Works great.  Thanks!
