### ISSUE TITLE
Lock acquisition period expired

### ISSUE THREAD

**Issue by pgpatel811** [MiloszKrajewski/Hangfire.Storage.MySql#4]
We were using **Hangfire.MySqlStorage** package, but with that we are facing connections and deadlocks related issues.

To sort out those issues, we are now using :
**Hangfire.AspNetCore : 1.7.18
Hangfire.Storage.MySql : 2.1.0-beta**

After updating these, we are now facing errors related to locks.
Error logs on production  : lock acquisition period expired.

Issues faced :
1. Sometimes jobs creation fails.
2. Sometimes jobs created but not scheduling.  (Jobs state : only Created)
3. Sometimes jobs en-queued but got failed. (Jobs state : Failed)
4. Recurring jobs never executing. (even by triggered from Dashboard)

Any help into this would be greatly appreciated.

**Comment by MiloszKrajewski** [comment]
After using Hangfire.MySqlStorage and you (XA) locked your tables and you did not rebuild them it is possible that even after changing library they are still locked.

I wrote this mini application to remove dealocks from previous runs (see: https://github.com/MiloszKrajewski/Hangfire.Storage.MySql/tree/master/src/XaRecover), so start with this one.

If it still does not work then I needs logs. I mean if something doesn't work then it throws exception, if it throws exceptions then there must be something in logs.

**Comment by pgpatel811** [comment]
Hey Milosz,

Thanks a lot for the quick response.
You are correct, i found deadlocks in my database.

The solution you provided to rollback those transactions works for me.
It was a headache for me since many days, as our jobs got stuck on production. I really appreciate your help in this.

**Comment by MiloszKrajewski** [comment]
No worries. Glad I could help.
