### ISSUE TITLE
FUNCTION db.release_all_locks does not exist

### ISSUE THREAD

**Issue by ejazmusavi** [MiloszKrajewski/Hangfire.Storage.MySql#6]
I am using asp.net core 5.0 with hangfire and hangfire.storage.mysql. It throw this error while creating a background job.

My database details are

    Server: 127.0.0.1 via TCP/IP
    Server type: MariaDB
    Server connection: SSL is not being used Documentation
    Server version: 10.4.22-MariaDB - mariadb.org binary distribution
    Protocol version: 10
    User: root@localhost
    Server charset: UTF-8 Unicode (utf8mb4)

**Comment by MiloszKrajewski** [comment]
https://mariadb.com/kb/en/release_all_locks/
> RELEASE_ALL_LOCKS was added in MariaDB 10.5.2.
